### PR TITLE
Zoom only on image opened fullscreen

### PR DESCRIPTION
**Pull request by PrimozRatej**
https://github.com/humhub/app-internal/issues/47

### CODE REVIEW

**Comment by luke-** [comment]
@PrimozRatej Seems there is a conflict, can you solve?

**Comment by marc-farre** [comment]
> @marc-farre Can you merge or should I?

Yes, I will when conflicts are resolved.
Should I check and merge all future PR in this `app` repository?

**Comment by luke-** [comment]
@marc-farre Would be cool, when you could check and merge PRs here!

**Comment by PrimozRatej** [comment]
@marc-farre ready.

**Review by marc-farre — APPROVED** [review]

**Comment by marc-farre** [comment]
@PrimozRatej Thanks!

**Pull request merged**
