### PR TITLE
Add latest userAgent and define applicationNameForUserAgent

### PR DESCRIPTION
**Pull request by PrimozRatej**
https://github.com/humhub/app-internal/issues/63
https://github.com/humhub/app/issues/244

### CODE REVIEW

**Review by marc-farre — APPROVED** [review]

**Comment by marc-farre** [comment]
@PrimozRatej Thanks!

**Comment by almarklein** [comment]
I see that merging this resulted in a new release. How long does it normally take for releases to land in TestFlight? It's currently on v1.0.120.

**Comment by PrimozRatej** [comment]
@almarklein current version released in the test tracks is [v1.0.123(https://github.com/humhub/app/tree/refs/tags/v1.0.123). It should also be available on TestFlight.

**Comment by almarklein** [comment]
Mmm, somehow my humhub app (via TestFlight) is stuck at v1.0.120, I have TestFlight's auto-updates turned on. Looks a bit like this: https://forums.developer.apple.com/forums/thread/96873

**Comment by almarklein** [comment]
Just got an email that the version is available, and could easily update in TestFlight. Thanks!

**Pull request merged**
